# Generated by Django 5.2 on 2025-05-03 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeoSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255, unique=True, verbose_name='URL или имя страницы')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('keywords', models.CharField(blank=True, max_length=255, verbose_name='Keywords')),
                ('og_title', models.CharField(blank=True, max_length=255, verbose_name='OG Title')),
                ('og_description', models.TextField(blank=True, verbose_name='OG Description')),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='seo/', verbose_name='OG Image')),
            ],
        ),
    ]
