# Generated by Django 5.2 on 2025-05-03 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_seosettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='seosettings',
            name='author',
            field=models.CharField(blank=True, max_length=100, verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='seosettings',
            name='canonical',
            field=models.URLField(blank=True, verbose_name='Canonical URL'),
        ),
        migrations.AddField(
            model_name='seosettings',
            name='custom_meta',
            field=models.TextField(blank=True, verbose_name='Дополнительные мета-теги (raw HTML)'),
        ),
        migrations.AddField(
            model_name='seosettings',
            name='og_image_height',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='OG Image Height'),
        ),
        migrations.AddField(
            model_name='seosettings',
            name='og_image_width',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='OG Image Width'),
        ),
        migrations.AddField(
            model_name='seosettings',
            name='og_locale',
            field=models.CharField(blank=True, default='ru_RU', max_length=20, verbose_name='OG Locale'),
        ),
        migrations.AddField(
            model_name='seosettings',
            name='og_site_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='OG Site Name'),
        ),
        migrations.AddField(
            model_name='seosettings',
            name='og_type',
            field=models.CharField(blank=True, default='website', max_length=50, verbose_name='OG Type'),
        ),
        migrations.AddField(
            model_name='seosettings',
            name='og_url',
            field=models.URLField(blank=True, verbose_name='OG URL'),
        ),
        migrations.AddField(
            model_name='seosettings',
            name='robots',
            field=models.CharField(blank=True, default='index, follow', max_length=50, verbose_name='Robots'),
        ),
        migrations.AddField(
            model_name='seosettings',
            name='schema_jsonld',
            field=models.TextField(blank=True, verbose_name='Schema.org JSON-LD'),
        ),
        migrations.AddField(
            model_name='seosettings',
            name='twitter_card',
            field=models.CharField(blank=True, default='summary_large_image', max_length=50, verbose_name='Twitter Card'),
        ),
        migrations.AddField(
            model_name='seosettings',
            name='twitter_creator',
            field=models.CharField(blank=True, max_length=100, verbose_name='Twitter Creator'),
        ),
        migrations.AddField(
            model_name='seosettings',
            name='twitter_site',
            field=models.CharField(blank=True, max_length=100, verbose_name='Twitter Site'),
        ),
    ]
