# Generated by Django 5.2 on 2025-05-05 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_review_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='review_type',
            field=models.CharField(choices=[('common', 'Общий'), ('coaching', 'Коучинг'), ('training', 'Тренинг'), ('masterclass', 'МК и семинары'), ('consulting', 'Консультации')], default='common', max_length=20, verbose_name='Тип отзыва'),
        ),
    ]
