SEO_DEFAULTS = {
    "title": "Главная — borodulin.expert",
    "description": "30 лет в банках, 15 в бизнесе. Помогаю запустить своё дело с уверенностью. Консультации, книги, инструменты для предпринимателей.",
    "keywords": "бизнес, тренер, Алексей Бородулин, предприниматель, банкротство, книги, консультации, инструменты, обучение, финансы, рост",
    "og_title": "borodulin.expert — бизнес-тренер Алексей Бородулин",
    "og_description": "30 лет в банках, 15 в бизнесе. Помогаю запустить своё дело с уверенностью.",
    "og_image": None,
    "og_type": "website",
    "og_site_name": "borodulin.expert",
    "og_locale": "ru_RU",
    "og_url": "/",
    "og_image_width": "800",
    "og_image_height": "600",
    "twitter_card": "summary_large_image",
    "twitter_site": "@borodulinexpert",
    "twitter_creator": "@borodulinexpert",
    "canonical": "/",
    "robots": "index, follow",
    "author": "Алексей Бородулин",
    "schema_jsonld": "",
    "custom_meta": "",
} 